// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: rcyewhhioqaxcjgusxjz

class SupabaseConfig {
  static const String supabaseUrl = 'https://rcyewhhioqaxcjgusxjz.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeWV3aGhpb3FheGNqZ3VzeGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NzY4NzcsImV4cCI6MjA3NTI1Mjg3N30.573CMTvKGj9wQghb43yHJ34vC5HU9HkaeRnp7tKyVXk';
}
